import {
  AlignmentType,
  Document,
  Footer,
  Header,
  HeadingLevel,
  Packer,
  PageNumber,
  Paragraph,
  Tab,
  TabStopPosition,
  TabStopType,
  TextRun,
} from 'docx'

import { DATA_VERSION } from './dataVersion'

const DISCLAIMER_TEXT =
  'GNCO is provided for informational and modeling purposes only. All jurisdiction recommendations, cost projections, suitability scores, and structural comparisons are illustrative estimates only. They do not constitute legal, tax, financial, or accounting advice, and do not represent a binding legal opinion. Actual formation costs, regulatory requirements, timelines, and tax treatments vary based on fund complexity, service provider selection, investor base, and applicable law. Always consult qualified legal counsel, tax advisors, and licensed service providers before making any fund structuring decisions. GNCO does not conduct AML, KYC, or investor accreditation checks. GNCO Ltd. All rights reserved.'

export interface BriefInput {
  generatedAt: string
  userEmail?: string
  brief: {
    strategy: string
    fundSize: string
    lpCount: number
    lpMix: string[]
    gpDomicile: string
  }
  recommendations: {
    jurisdiction: string
    vehicleType: string
    rank: number
    reasoning: string
    estimatedFormationCost: { min: number; max: number }
    estimatedTimelineWeeks: { min: number; max: number }
  }[]
  jurisdictionData?: {
    regulator?: string
    regulatorUrl?: string
    annualCostMin?: number
    annualCostMax?: number
    taxTreaties?: string[]
    taxHeadline?: string
    timelines?: string
    keyCompliance?: string
    serviceProviders?: string
  }
}

function usd(n: number) {
  return `USD ${n.toLocaleString()}`
}

export async function generateBriefDocx(input: BriefInput): Promise<Buffer> {
  const { brief, recommendations, jurisdictionData } = input
  const top = recommendations[0]
  const second = recommendations[1]
  const third = recommendations[2]
  const date = input.generatedAt.slice(0, 10)

  const footer = new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: `Generated by GNCO Architect Engine ${DATA_VERSION.label} | gnconew.vercel.app`,
            size: 16,
            color: '888888',
          }),
        ],
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: 'Not legal advice. Review with qualified counsel.',
            size: 16,
            color: '888888',
          }),
          new TextRun({ children: [new Tab()] }),
          new TextRun({
            text: 'Page ',
            size: 16,
            color: '888888',
          }),
          new TextRun({
            children: [PageNumber.CURRENT],
            size: 16,
            color: '888888',
          }),
        ],
        tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
      }),
    ],
  })

  const doc = new Document({
    sections: [
      // Cover page
      {
        properties: {},
        headers: {
          default: new Header({ children: [] }),
        },
        footers: { default: footer },
        children: [
          new Paragraph({ spacing: { before: 4000 } }),
          new Paragraph({
            children: [new TextRun({ text: 'Fund Structure Attorney Brief', bold: true, size: 48, color: '0F1A2E' })],
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            children: [new TextRun({ text: 'Prepared by GNCO Architect Engine', size: 28, color: '666666' })],
            alignment: AlignmentType.CENTER,
            spacing: { before: 200 },
          }),
          new Paragraph({
            children: [new TextRun({ text: `For: ${input.userEmail ?? 'Confidential'}`, size: 24, color: '666666' })],
            alignment: AlignmentType.CENTER,
            spacing: { before: 200 },
          }),
          new Paragraph({
            children: [new TextRun({ text: `Date: ${date}`, size: 24, color: '666666' })],
            alignment: AlignmentType.CENTER,
            spacing: { before: 100 },
          }),
          new Paragraph({
            children: [new TextRun({ text: `Data Version: v${DATA_VERSION.version} | Last updated: ${DATA_VERSION.lastUpdated}`, size: 20, color: '888888' })],
            alignment: AlignmentType.CENTER,
            spacing: { before: 200 },
          }),
          new Paragraph({ spacing: { before: 1200 } }),
          new Paragraph({
            children: [new TextRun({ text: 'DISCLAIMER', bold: true, size: 18, color: '999999' })],
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            children: [new TextRun({ text: DISCLAIMER_TEXT, size: 16, color: '999999', italics: true })],
            alignment: AlignmentType.JUSTIFIED,
            spacing: { before: 100 },
          }),
        ],
      },

      // Section 1: Summary Recommendation
      {
        footers: { default: footer },
        children: [
          new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: '1. Summary Recommendation', bold: true })] }),
          bullet(`Recommended jurisdiction: ${top.jurisdiction}`),
          bullet(`Recommended vehicle: ${top.vehicleType}`),
          bullet(`Suitability rationale: ${top.reasoning}`),
          bullet(`Fund strategy: ${brief.strategy}`),
          bullet(`Fund size: ${brief.fundSize}`),
          bullet(`GP domicile: ${brief.gpDomicile}`),
          bullet(`LP count: ${brief.lpCount}`),
          bullet(`LP mix: ${brief.lpMix.join(', ') || 'Mixed'}`),
        ],
      },

      // Section 2: Cost Model
      {
        footers: { default: footer },
        children: [
          new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: '2. Cost Model', bold: true })] }),
          bullet(`Estimated formation cost: ${usd(top.estimatedFormationCost.min)} – ${usd(top.estimatedFormationCost.max)}`),
          bullet(`Estimated annual operating cost: ${jurisdictionData?.annualCostMin && jurisdictionData?.annualCostMax ? `${usd(jurisdictionData.annualCostMin)} – ${usd(jurisdictionData.annualCostMax)}` : 'To be scoped during counsel engagement'}`),
          new Paragraph({ spacing: { before: 200 } }),
          new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: '5-Year Cost Projection', bold: true })] }),
          ...[1, 2, 3, 4, 5].map((year) => {
            const annualMin = jurisdictionData?.annualCostMin ?? top.estimatedFormationCost.min
            const annualMax = jurisdictionData?.annualCostMax ?? top.estimatedFormationCost.max
            const formMin = year === 1 ? top.estimatedFormationCost.min : 0
            const formMax = year === 1 ? top.estimatedFormationCost.max : 0
            return bullet(`Year ${year}: ${usd(formMin + annualMin * year)} – ${usd(formMax + annualMax * year)} (cumulative)`)
          }),
        ],
      },

      // Section 3: LP Tax Impact
      {
        footers: { default: footer },
        children: [
          new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: '3. LP Tax Impact', bold: true })] }),
          bullet(`Tax headline: ${jurisdictionData?.taxHeadline ?? 'Review local direct and withholding tax profile.'}`),
          bullet(`LP domicile considerations: ${brief.lpMix.length > 0 ? brief.lpMix.join(', ') : 'Mixed LP profile — review by counsel by domicile.'}`),
          bullet('WHT implications: Taxable investors, tax-exempt LPs, and sovereign/foundation capital should each be analyzed for treaty eligibility and reclaim mechanics.'),
          bullet(`Key treaty network: ${jurisdictionData?.taxTreaties?.join(', ') ?? 'Treaty analysis depends on LP domicile and asset jurisdiction.'}`),
        ],
      },

      // Section 4: Comparison (Top 3)
      {
        footers: { default: footer },
        children: [
          new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: '4. Top 3 Jurisdiction Comparison', bold: true })] }),
          ...[top, second, third].filter(Boolean).map((rec, i) =>
            new Paragraph({
              spacing: { before: 200 },
              children: [
                new TextRun({ text: `#${i + 1} — ${rec.jurisdiction}`, bold: true, size: 24 }),
                new TextRun({ text: `\nVehicle: ${rec.vehicleType}`, break: 1, size: 22 }),
                new TextRun({ text: `\nFormation cost: ${usd(rec.estimatedFormationCost.min)} – ${usd(rec.estimatedFormationCost.max)}`, break: 1, size: 22 }),
                new TextRun({ text: `\nTimeline: ${rec.estimatedTimelineWeeks.min}–${rec.estimatedTimelineWeeks.max} weeks`, break: 1, size: 22 }),
                new TextRun({ text: `\nRationale: ${rec.reasoning}`, break: 1, size: 22 }),
              ],
            }),
          ),
        ],
      },

      // Section 5: Recommended Next Steps
      {
        footers: { default: footer },
        children: [
          new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: '5. Recommended Next Steps', bold: true })] }),
          bullet(`Engage licensed counsel in ${top.jurisdiction} to validate structure recommendation.`),
          bullet(`Obtain regulatory guidance from ${jurisdictionData?.regulator ?? 'the local regulator'}.`),
          bullet('Confirm LP-level WHT treatment with tax counsel for each LP domicile.'),
          bullet('Appoint administrator, auditor, and legal counsel.'),
          bullet('Prepare constitutive documents and required regulatory filings.'),
          bullet('Establish AML/KYC framework and investor onboarding workflow.'),
          bullet('Set first-close timeline and LP communication cadence.'),
          bullet(`Review this brief against assumptions — data version: v${DATA_VERSION.version}, last updated: ${DATA_VERSION.lastUpdated}.`),
        ],
      },
    ],
  })

  return Buffer.from(await Packer.toBuffer(doc))
}

function bullet(text: string): Paragraph {
  return new Paragraph({
    spacing: { before: 80 },
    children: [new TextRun({ text: `• ${text}`, size: 22 })],
  })
}
