import type { JurisdictionProfile } from './types'

export const JURISDICTIONS: JurisdictionProfile[] = [
  {
    id: 'cayman-islands',
    name: 'Cayman Islands',
    region: 'americas',
    flag: '🇰🇾',
    primaryVehicles: ['Exempted Limited Partnership (ELP)', 'Exempted Company', 'Segregated Portfolio Company (SPC)', 'LLC'],
    regulator: 'Cayman Islands Monetary Authority (CIMA)',
    regulatorUrl: 'https://www.cima.ky',
    taxTreatyStrength: 'limited',
    setupTimeWeeks: { min: 1, max: 2 },
    annualCostRange: { min: 20000, max: 40000 },
    formationCostRange: { min: 15000, max: 30000 },
    suitabilityScore: 89,
    bestFor: ['Global PE and hedge structures', 'Fast formation', 'Institutional LP familiarity'],
    notIdealFor: ['Treaty-heavy withholding optimization'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['Apex Group', 'Maples Fund Services', 'MUFG Investor Services'],
      lawFirms: ['Maples and Calder', 'Walkers', 'Ogier'],
      auditors: ['KPMG', 'EY'],
    },
    taxTreaties: ['United Kingdom', 'Ireland', 'Japan'],
    fatcaStatus: 'FATCA and CRS reporting required.',
    notes: 'Default offshore choice for many PE/VC managers with strong legal predictability.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'Aggregated service provider quotes + CIMA fee schedule',
  },
  {
    id: 'luxembourg',
    name: 'Luxembourg',
    region: 'europe',
    flag: '🇱🇺',
    primaryVehicles: ['RAIF', 'SIF', 'SICAR', 'SCSp'],
    regulator: 'Commission de Surveillance du Secteur Financier (CSSF)',
    regulatorUrl: 'https://www.cssf.lu',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 2, max: 12 },
    annualCostRange: { min: 80000, max: 200000 },
    formationCostRange: { min: 50000, max: 120000 },
    suitabilityScore: 82,
    bestFor: ['EU fundraising and passporting', 'Institutional allocators', 'Cross-border treaty planning'],
    notIdealFor: ['Ultra-lean first-time launches'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['Alter Domus', 'IQ-EQ', 'Aztec Group'],
      lawFirms: ['Arendt & Medernach', 'Elvinger Hoss Prussen', 'A&O Shearman Luxembourg'],
      auditors: ['PwC', 'Deloitte'],
    },
    taxTreaties: ['Germany', 'France', 'United States', 'Netherlands', 'Switzerland'],
    fatcaStatus: 'FATCA and CRS reporting required.',
    notes: 'RAIF remains one of the most practical fast-regulatory EU alternatives vehicles.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'Aggregated service provider quotes + CSSF fee schedule',
  },
  {
    id: 'delaware',
    name: 'Delaware (USA)',
    region: 'americas',
    flag: '🇺🇸',
    primaryVehicles: ['Delaware Limited Partnership', 'Delaware LLC', 'Delaware Statutory Trust'],
    regulator: 'SEC (federal) + Delaware Division of Corporations',
    regulatorUrl: 'https://www.sec.gov',
    taxTreatyStrength: 'limited',
    setupTimeWeeks: { min: 1, max: 7 },
    annualCostRange: { min: 15000, max: 50000 },
    formationCostRange: { min: 5000, max: 15000 },
    suitabilityScore: 87,
    bestFor: ['US-centric LP base', 'VC and PE fund formations', 'Fast state-level launch'],
    notIdealFor: ['Non-US LPs sensitive to US-source withholding'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['SEI', 'SS&C GlobeOp', 'Apex Group'],
      lawFirms: ['Kirkland & Ellis', 'Latham & Watkins', 'Goodwin Procter'],
      auditors: ['KPMG', 'RSM'],
    },
    taxTreaties: ['United Kingdom', 'Canada', 'Germany', 'Japan'],
    fatcaStatus: 'US FATCA framework applies; CRS not adopted by US.',
    notes: 'Dominant US private fund formation state due to speed and legal depth.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'SEC fee schedule + Delaware Division of Corporations + service provider estimates',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    region: 'asia-pacific',
    flag: '🇸🇬',
    primaryVehicles: ['Variable Capital Company (VCC)', 'Singapore Limited Partnership', 'Unit Trust'],
    regulator: 'Monetary Authority of Singapore (MAS)',
    regulatorUrl: 'https://www.mas.gov.sg',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 1, max: 24 },
    annualCostRange: { min: 30000, max: 100000 },
    formationCostRange: { min: 15000, max: 40000 },
    suitabilityScore: 85,
    bestFor: ['Asia-Pacific mandates', 'Family office capital', 'Manager substance in APAC'],
    notIdealFor: ['Teams without local licensing or partner infrastructure'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['HSBC Securities Services', 'Apex Group', 'Tricor'],
      lawFirms: ['Allen & Gledhill', 'WongPartnership', 'Rajah & Tann'],
      auditors: ['PwC', 'EY'],
    },
    taxTreaties: ['China', 'India', 'Japan', 'United Kingdom', 'Australia'],
    fatcaStatus: 'Model 1 IGA with US; CRS implemented.',
    notes: 'VCC is now a mainstream private-fund and multi-sub-fund platform in Asia.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'MAS fee schedule + service provider estimates',
  },
  {
    id: 'ireland',
    name: 'Ireland',
    region: 'europe',
    flag: '🇮🇪',
    primaryVehicles: ['QIAIF', 'ICAV', 'ILP', 'UCITS'],
    regulator: 'Central Bank of Ireland (CBI)',
    regulatorUrl: 'https://www.centralbank.ie',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 1, max: 12 },
    annualCostRange: { min: 80000, max: 180000 },
    formationCostRange: { min: 50000, max: 100000 },
    suitabilityScore: 87,
    bestFor: ['EU allocator access', 'AIFMD passporting', 'Institutional credit and real asset funds'],
    notIdealFor: ['Ultra-low budget launches'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['State Street', 'Northern Trust', 'Citco'],
      lawFirms: ['Matheson', 'A&L Goodbody', 'Arthur Cox'],
      auditors: ['KPMG', 'PwC'],
    },
    taxTreaties: ['United States', 'United Kingdom', 'Germany', 'France'],
    fatcaStatus: 'Model 1 IGA with US; CRS implemented.',
    notes: 'QIAIF fast-track remains a strong institutional launch pathway.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'Service provider estimates + CBI fee schedule',
  },
  {
    id: 'bvi',
    name: 'British Virgin Islands',
    region: 'americas',
    flag: '🇻🇬',
    primaryVehicles: ['BVI Business Company', 'BVI Limited Partnership', 'Private Fund', 'Professional Fund'],
    regulator: 'BVI Financial Services Commission (FSC)',
    regulatorUrl: 'https://www.bvifsc.vg',
    taxTreatyStrength: 'limited',
    setupTimeWeeks: { min: 1, max: 2 },
    annualCostRange: { min: 12000, max: 25000 },
    formationCostRange: { min: 8000, max: 18000 },
    suitabilityScore: 71,
    bestFor: ['Cost-efficient offshore launches', 'Smaller private funds', 'Quick setup cycles'],
    notIdealFor: ['Treaty-dependent tax structures'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['Apex Group', 'Maples FS', 'Trident Trust'],
      lawFirms: ['Appleby', 'Ogier', 'Walkers'],
      auditors: ['KPMG', 'BDO'],
    },
    taxTreaties: ['United Kingdom', 'Switzerland'],
    fatcaStatus: 'FATCA and CRS reporting required.',
    notes: 'Very fast and flexible for private/professional fund products.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'BVI FSC fee schedule + service provider estimates',
  },
  {
    id: 'jersey',
    name: 'Jersey',
    region: 'europe',
    flag: '🇯🇪',
    primaryVehicles: ['Jersey Private Fund', 'Jersey Expert Fund', 'Jersey Limited Partnership'],
    regulator: 'Jersey Financial Services Commission (JFSC)',
    regulatorUrl: 'https://www.jerseyfsc.org',
    taxTreatyStrength: 'medium',
    setupTimeWeeks: { min: 1, max: 10 },
    annualCostRange: { min: 30000, max: 80000 },
    formationCostRange: { min: 20000, max: 50000 },
    suitabilityScore: 79,
    bestFor: ['UK and EU LP familiarity', 'Rapid private fund launch', 'Real asset and PE structures'],
    notIdealFor: ['Managers needing full EU passport by default'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['JTC', 'Apex Group', 'Aztec Group'],
      lawFirms: ['Carey Olsen', 'Mourant', 'Ogier'],
      auditors: ['PwC', 'KPMG'],
    },
    taxTreaties: ['United Kingdom', 'UAE'],
    fatcaStatus: 'FATCA and CRS reporting required.',
    notes: 'JPF 48-hour route remains one of the quickest globally.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'JFSC fee schedule + service provider estimates',
  },
  {
    id: 'guernsey',
    name: 'Guernsey',
    region: 'europe',
    flag: '🇬🇬',
    primaryVehicles: ['Private Investment Fund (PIF)', 'Registered Closed-Ended Investment Scheme', 'Guernsey LP'],
    regulator: 'Guernsey Financial Services Commission (GFSC)',
    regulatorUrl: 'https://www.gfsc.gg',
    taxTreatyStrength: 'medium',
    setupTimeWeeks: { min: 1, max: 12 },
    annualCostRange: { min: 25000, max: 70000 },
    formationCostRange: { min: 18000, max: 45000 },
    suitabilityScore: 76,
    bestFor: ['Infrastructure and real assets', 'UK and European investor bases', 'Fast private fund registration'],
    notIdealFor: ['Managers requiring deep onshore EU fund admin depth'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['Apex Group', 'JTC', 'IQ-EQ'],
      lawFirms: ['Mourant', 'Carey Olsen', 'Ogier'],
      auditors: ['KPMG', 'EY'],
    },
    taxTreaties: ['United Kingdom', 'Jersey'],
    fatcaStatus: 'FATCA and CRS reporting required.',
    notes: 'Pragmatic regime with strong fit for private and listed alternative funds.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'GFSC fee schedule + service provider estimates',
  },
  {
    id: 'mauritius',
    name: 'Mauritius',
    region: 'middle-east',
    flag: '🇲🇺',
    primaryVehicles: ['Global Business Company (GBC)', 'Variable Capital Company (VCC)', 'Collective Investment Scheme'],
    regulator: 'Financial Services Commission Mauritius (FSC)',
    regulatorUrl: 'https://www.fscmauritius.org',
    taxTreatyStrength: 'medium',
    setupTimeWeeks: { min: 1, max: 6 },
    annualCostRange: { min: 15000, max: 40000 },
    formationCostRange: { min: 8000, max: 20000 },
    suitabilityScore: 74,
    bestFor: ['Africa-focused deployment', 'Treaty-oriented regional investing', 'Cost-conscious cross-border platforms'],
    notIdealFor: ['India structures assuming pre-2017 treaty economics'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['IQ-EQ Mauritius', 'Apex Group Mauritius', 'Intercontinental Trust'],
      lawFirms: ['BLC Robert', 'ENSafrica Mauritius', 'Appleby Mauritius'],
      auditors: ['EY', 'BDO'],
    },
    taxTreaties: ['India', 'South Africa', 'UAE', 'China', 'France'],
    fatcaStatus: 'Model 1 IGA with US; CRS implemented.',
    notes: 'Still relevant for Africa corridors with substance and treaty planning.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'FSC Mauritius fee schedule + service provider estimates',
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong',
    region: 'asia-pacific',
    flag: '🇭🇰',
    primaryVehicles: ['Limited Partnership Fund (LPF)', 'Open-ended Fund Company (OFC)', 'Unit Trust'],
    regulator: 'Securities and Futures Commission (SFC)',
    regulatorUrl: 'https://www.sfc.hk',
    taxTreatyStrength: 'medium',
    setupTimeWeeks: { min: 1, max: 24 },
    annualCostRange: { min: 100000, max: 300000 },
    formationCostRange: { min: 50000, max: 150000 },
    suitabilityScore: 80,
    bestFor: ['Greater China and APAC investment platforms', 'Fast LPF setup', 'Carried interest concession structures'],
    notIdealFor: ['Managers without SFC licensing pathway'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['Vistra', 'Tricor', 'HSBC Securities Services'],
      lawFirms: ['Deacons', 'Mayer Brown', 'Sidley Austin'],
      auditors: ['PwC', 'KPMG'],
    },
    taxTreaties: ['China', 'Singapore', 'Japan', 'United Kingdom', 'Netherlands'],
    fatcaStatus: 'Model 2 IGA with US; CRS implemented.',
    notes: 'LPF is fast; manager licensing is often the primary critical path item.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'SFC fee schedule + service provider estimates',
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    region: 'europe',
    flag: '🇳🇱',
    primaryVehicles: ['FGR', 'CV', 'B.V./N.V.'],
    regulator: 'Autoriteit Financiële Markten (AFM) + De Nederlandsche Bank (DNB)',
    regulatorUrl: 'https://www.afm.nl',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 1, max: 24 },
    annualCostRange: { min: 40000, max: 120000 },
    formationCostRange: { min: 3000, max: 15000 },
    suitabilityScore: 78,
    bestFor: ['EU institutional mandates', 'Holding and feeder layers', 'Treaty-supported structures'],
    notIdealFor: ['Managers seeking minimal substance and compliance footprint'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['TMF Group', 'Alter Domus', 'IQ-EQ'],
      lawFirms: ['Loyens & Loeff', 'De Brauw', 'Stibbe'],
      auditors: ['KPMG', 'Deloitte'],
    },
    taxTreaties: ['United States', 'United Kingdom', 'Germany', 'France', 'Japan'],
    fatcaStatus: 'Model 1 IGA with US; CRS implemented.',
    notes: 'Often used as a treaty-efficient intermediate layer with robust substance.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'AFM/DNB fee schedules + service provider estimates',
  },
  {
    id: 'bermuda',
    name: 'Bermuda',
    region: 'americas',
    flag: '🇧🇲',
    primaryVehicles: ['Exempted Limited Partnership (ELP)', 'Segregated Accounts Company (SAC)', 'Exempted Company'],
    regulator: 'Bermuda Monetary Authority (BMA)',
    regulatorUrl: 'https://www.bma.bm',
    taxTreatyStrength: 'limited',
    setupTimeWeeks: { min: 1, max: 2 },
    annualCostRange: { min: 15000, max: 40000 },
    formationCostRange: { min: 10000, max: 25000 },
    suitabilityScore: 75,
    bestFor: ['Insurance-linked funds', 'Tax-neutral offshore formations', 'Fast fund approval routes'],
    notIdealFor: ['Managers needing broad treaty access'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['Apex Group', 'Conyers', 'Maples Fund Services'],
      lawFirms: ['Conyers', 'Walkers', 'Appleby'],
      auditors: ['KPMG', 'EY'],
    },
    taxTreaties: ['United Kingdom'],
    fatcaStatus: 'FATCA and CRS reporting required.',
    notes: 'Leading domicile for ILS and catastrophe-linked alternatives.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'BMA fee schedule + service provider estimates',
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    region: 'europe',
    flag: '🇨🇭',
    primaryVehicles: ['L-QIF', 'SICAV', 'KmGK'],
    regulator: 'Swiss Financial Market Supervisory Authority (FINMA)',
    regulatorUrl: 'https://www.finma.ch',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 12, max: 52 },
    annualCostRange: { min: 50000, max: 150000 },
    formationCostRange: { min: 30000, max: 80000 },
    suitabilityScore: 77,
    bestFor: ['Swiss institutional ecosystems', 'Qualified-investor funds via L-QIF', 'Manager substance and governance'],
    notIdealFor: ['Low-cost first-time structures'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['CACEIS Switzerland', 'Swissquote Fund Services', 'SGSS Switzerland'],
      lawFirms: ['Lenz & Staehelin', 'Bär & Karrer', 'Niederer Kraft Frey'],
      auditors: ['EY', 'KPMG'],
    },
    taxTreaties: ['Germany', 'France', 'United Kingdom', 'United States', 'Netherlands'],
    fatcaStatus: 'Model 2 IGA with US; CRS implemented.',
    notes: 'L-QIF materially improved speed-to-market for qualified investor products.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'FINMA fee schedule + service provider estimates',
  },
  {
    id: 'cyprus',
    name: 'Cyprus',
    region: 'europe',
    flag: '🇨🇾',
    primaryVehicles: ['AIF', 'AIFLNP', 'Registered AIF', 'Cyprus LP'],
    regulator: 'Cyprus Securities and Exchange Commission (CySEC)',
    regulatorUrl: 'https://www.cysec.gov.cy',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 2, max: 24 },
    annualCostRange: { min: 25000, max: 70000 },
    formationCostRange: { min: 15000, max: 40000 },
    suitabilityScore: 83,
    bestFor: ['EU passports with lower setup costs', 'GP relocation and non-dom planning', 'Mid-market private funds'],
    notIdealFor: ['Managers requiring deepest EU service-provider stack'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['Apex Group Cyprus', 'Map S. Platis', 'KPMG Cyprus'],
      lawFirms: ['Chrysses Demetriades', 'Elias Neocleous', 'Patrikios Pavlou'],
      auditors: ['PwC', 'KPMG'],
    },
    taxTreaties: ['United Kingdom', 'France', 'Germany', 'UAE', 'India'],
    fatcaStatus: 'Model 1 IGA with US; CRS implemented.',
    notes: 'AIFLNP and Registered AIF routes offer practical launch speed within EU rules.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'CySEC fee schedule + service provider estimates',
  },
  {
    id: 'difc',
    name: 'Dubai (DIFC)',
    region: 'middle-east',
    flag: '🇦🇪',
    primaryVehicles: ['DIFC Limited Partnership', 'Exempt Fund', 'Qualified Investor Fund (QIF)'],
    regulator: 'Dubai Financial Services Authority (DFSA)',
    regulatorUrl: 'https://www.dfsa.ae',
    taxTreatyStrength: 'high',
    setupTimeWeeks: { min: 1, max: 24 },
    annualCostRange: { min: 30000, max: 80000 },
    formationCostRange: { min: 20000, max: 50000 },
    suitabilityScore: 81,
    bestFor: ['GCC and MENA LP fundraising', 'Common-law regional hub', 'Tax-efficient manager base'],
    notIdealFor: ['Managers without DFSA licensing timeline tolerance'],
    coverageStatus: 'full',
    keyServiceProviders: {
      administrators: ['Apex Group', 'Vistra', 'TMF Group'],
      lawFirms: ['Clifford Chance', 'Al Tamimi', 'Hogan Lovells'],
      auditors: ['Deloitte', 'EY'],
    },
    taxTreaties: ['United Kingdom', 'India', 'France', 'Germany', 'Singapore'],
    fatcaStatus: 'FATCA and CRS reporting required.',
    notes: 'Growing center for GCC allocators with strong DFSA supervision and 0% DIFC tax framework.',
    strategies: ['PE', 'RE', 'VC', 'PC'],
    dataVersion: '2.1',
    lastUpdated: '2026-02-19',
    sourceNote: 'DFSA fee schedule + service provider estimates',
  },
]
